### ISSUE TITLE
[BUG] Module isn't  properly recognised by Magisk

### ISSUE THREAD

**Issue by HarriBuh** [Magisk-Modules-Alt-Repo/Bye-Blur#1]
Google Pixel 7
Android 15
Magisk 28001

![markup_1000029987.png](https://github.com/user-attachments/assets/e1e96b45-7672-499e-9a81-5dd2c4f090e7)

This is the only possible place for the installed module.

**Comment by DerGoogler** [comment]
@HarriBuh, this module doesn't have an active maintainer.

**Comment by HarriBuh** [comment]
So nobody cares about it? Wtf is this 😂 Thanks for letting me know anyway.

**Comment by DerGoogler** [comment]
Yeah, idk why 😅
